---
title: "automation_of_updates"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{automation_of_updates}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


To be able to automate the dataset updates, the data R package needs to be in place first. If that is not the case, follow the instructions in the vignette `initialise_a_ts_archive.Rmd`.

To be able to automatically update datasets, deloRean builds a github actions configuration into your data package. To inspect this, navigate to `.github/workflows/ci.yaml`. More on this later. For this github action config to run properly, you need to configure a couple of things. 

## Runtime Environment Prerequisites

<!-- are we scaring people with this? -->
### Schedule
- Set a [schedule](https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows?search-overlay-input=cron#schedule) which specifies when your dataset should be checked for updates. We use POSIX cron syntax for this. Some examples are:

“At 00:00 on every day-of-week from Monday through Friday.”

```yaml
on:
  schedule:
    - cron: "0 0 * * 1-5"
```

"At 00:00 on the first day of the month"

```yaml
on:
  schedule:
    - cron: "0 0 1 * *"
```
[Here](https://crontab.guru/examples.html) are a couple more common use cases.


### ARM R Image

the github actions configuration uses a lightweight ARM Image to be able to run R 
<!-- TODO: Anything else to mention here? -->


## Build data R package

Your data R package currently looks like this:

```
├── .github
│   ├── workflows
│   │   ├── ci.yaml
├── data-raw
│   ├── series.csv
├── DESCRIPTION
├── NAMESPACE
├── R
│   ├── handle_update.R
│   ├── is_update_needed.R
│   ├── process_data.R
│   ├── dataset_write.R # previously (`dataset_update.R`)
├── README.md
```

### End-User Written Functions

In the R folder are boiler plated R functions. Most importantly, you have `handle_update` which calls the functions: `is_update_needed` which compares the dataset's LAST_UPDATE (aka the date written in this file, which is the last time the dataset was updated) with the data publisher's last update, and if `is_update_needed` returns True, then `process_data` ensures that the dataset is downloaded and is processed s.t. it has the same format as needed, and finally: `dataset_write` writes the data to disk (and then the gha pushes the final changes).

### Inside process_data.R

This function (?) processes data into a form that allows to map keys to folders. It also does a catalogue update (where it checks which keys are in this data package, and if these need to be updated). For example: in case we get a new dataset into this data package i.e. ch.kof.globalbaro -> coincident & leading, not just leading. 
<!-- TODO: Also dataseet specific metainformation -->

```r
opentimeseries::key_to_path()
```
<!--
One recommendation is to use the opentimeseries R package's `key_to_path` function, and `path_to_key` function. The former uses the key, such as `ch.kof.globalbaro` and nests it into the archive structure. I.e. 

TODO: where is this archive structure used? for users building their own data structure, yes, but many don't -> use opentimeseries to fetch data

-->

```
├── ch
│   ├── kof
│   │   ├── globalbaro
```

### Inside dataset write 

Used to the the `dataset_update` function. it just writes the new time series to the directory, then done.


### Understand & Adapt your GHA config 

<!-- TODO: in archive_init we also write a helper function: run_update ?? outdated -->

To be able to use your newly created data package well, you need to understand, how the update process works well. We already teasered above, that it uses the github action configuration, and that your data package needs "end-user written functions". But let's put it all together. 


**HOW UPDATING WORKS**: In your github actions configuration you are using a scheduler (described above) which specifies when the github actions script is run. This script, when run: takes your git repository (= your data R package) and installs the necessary dependencies and R packages needed to update your data package, and then runs the function `handle_update` which you have written to your data package. Effectively, `handle_update` checks whether an update is needed (`is_update_needed`) and if True, calls `process_data` which then downloads, and processes the data so it is in the unified tsl format. Finally, the `write_open_ts` function (from opentimeseries) writes the new dataset version to disk, and then the github action handles the rest (=commit, push)


<!-- TODO: wrote this before discussion on 23.1. Is this still necessary -->
**Step-by-Step Explanation:**
- provide explanation of boilerplated GHA config
- specify cron job (if deloRean default doesn't work for you)
- specify which R pkgs you need to install


<!-- ### TODO: timeseries specific metadata information (write boilerplated & docs for end-users) -->