name: Update Data


# workflow triggered both manually and by schedule
on:
  workflow-dispatch:
  schedule:
    - cron:"15 4,5, * * *"
# switching on to the above will trigger at 4:15, on every 5th day of the month


jobs:
  setup:
    runs-on: ubuntu-22.04-arm
    container: devxygmbh/r-alpine:4-3.21
    steps:
      - name: Manual Checkout
        run: |
          apk update
          apk add git
          git clone --depth=1 https://github.com/${{ github.repository }}.git .

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory $(pwd)

      - name: Install system dependencies
        run: |
          apk add harfbuzz-dev fribidi-dev
      - name: Set Repo
        run: |
          R -e 'options("repos")'
      - name: Install packages
        run: |
          R -q -e 'install.packages("pak")'
          R -q -e 'pak::pkg_install("remotes")'
          R -q -e 'remotes::install_github("opentsi/opentimeseries")'
          R -q -e 'remotes::install_github("${{ github.repository }}")'

      # TODO: build this R data package
      - name: handle_update
        run: |
          R -q -e '${{ github.event.repository.name }}::handle_update()'
      - name: Commit and push changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "update data"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
